<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Assets\01.png" />
    <None Remove="Assets\02.png" />
    <None Remove="Assets\03.png" />
    <None Remove="Assets\07.png" />
    <None Remove="Assets\08.png" />
    <None Remove="Assets\10.png" />
    <None Remove="Assets\104.jpg" />
    <None Remove="Assets\105.jpg" />
    <None Remove="Assets\106.jpg" />
    <None Remove="Assets\107.jpg" />
    <None Remove="Assets\108.jpg" />
    <None Remove="Assets\109.jpg" />
    <None Remove="Assets\11.png" />
    <None Remove="Assets\114.png" />
    <None Remove="Assets\115.jpg" />
    <None Remove="Assets\116.jpg" />
    <None Remove="Assets\117.jpg" />
    <None Remove="Assets\118.jpg" />
    <None Remove="Assets\119.jpg" />
    <None Remove="Assets\12.png" />
    <None Remove="Assets\120.jpg" />
    <None Remove="Assets\121.jpg" />
    <None Remove="Assets\122.jpg" />
    <None Remove="Assets\123.jpg" />
    <None Remove="Assets\13.png" />
    <None Remove="Assets\15.png" />
    <None Remove="Assets\470.jpg" />
    <None Remove="Assets\471.jpg" />
    <None Remove="Assets\472.jpg" />
    <None Remove="Assets\473.jpg" />
    <None Remove="Assets\474.jpg" />
    <None Remove="Assets\475.jpg" />
    <None Remove="Assets\476.jpg" />
    <None Remove="Assets\480.jpg" />
    <None Remove="Assets\481.jpg" />
    <None Remove="Assets\482.jpg" />
    <None Remove="Assets\483.jpg" />
    <None Remove="Assets\484.jpg" />
    <None Remove="Assets\485.jpg" />
    <None Remove="Assets\486.jpg" />
    <None Remove="Assets\490.jpg" />
    <None Remove="Assets\491.jpg" />
    <None Remove="Assets\492.jpg" />
    <None Remove="Assets\493.jpg" />
    <None Remove="Assets\494.jpg" />
    <None Remove="Assets\495.jpg" />
    <None Remove="Assets\496.jpg" />
    <None Remove="Assets\530.jpg" />
    <None Remove="Assets\531.jpg" />
    <None Remove="Assets\532.jpg" />
    <None Remove="Assets\533.jpg" />
    <None Remove="Assets\534.jpg" />
    <None Remove="Assets\535.jpg" />
    <None Remove="Assets\536.jpg" />
    <None Remove="Assets\540.jpg" />
    <None Remove="Assets\545.png" />
    <None Remove="Assets\546.jpg" />
    <None Remove="Assets\Dry_0.jpg" />
    <None Remove="Assets\Dry_10.jpg" />
    <None Remove="Assets\Dry_11.jpg" />
    <None Remove="Assets\Istiratel_Err.jpg" />
    <None Remove="Assets\Istiratel_Stop.jpg" />
    <None Remove="Assets\Istiratel_Work.jpg" />
    <None Remove="Assets\SysRet_Err.jpg" />
    <None Remove="Assets\SysRet_Stop.jpg" />
    <None Remove="Assets\SysRet_Work.jpg" />
    <None Remove="Resourses\Styles\Validation\ValidationErrors.xaml" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaXaml Include="Resourses\Styles\Validation\ValidationErrors.xaml">
      <Generator>MSBuild:Compile</Generator>
    </AvaloniaXaml>
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="Avalonia.Themes.Fluent" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.10.18" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="0.10.18" />
    <PackageReference Include="Avalonia.Desktop" Version="0.10.18" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="0.10.18" />
    <PackageReference Include="Avalonia.Xaml.Behaviors" Version="0.10.18" />
    <PackageReference Include="Material.Icons" Version="1.0.2" />
    <PackageReference Include="Material.Icons.Avalonia" Version="1.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.0" />
    <PackageReference Include="NP.Avalonia.Visuals" Version="1.0.38" />
    <PackageReference Include="XamlNameReferenceGenerator" Version="1.6.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>
  

  <ItemGroup>
    <UpToDateCheckInput Remove="UserControls\HighBar\ConnectIndicatorControl.axaml" />
  </ItemGroup>
  

  <ItemGroup>
    <UpToDateCheckInput Remove="UserControls\Plc\PlcIndicationControl.axaml" />
  </ItemGroup>
  

  <ItemGroup>
    <Compile Update="UserControls\Plc\Statuses\ProbotborStatus.axaml.cs">
      <DependentUpon>ProbotborStatus.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
  

  <ItemGroup>
    <None Update="vissma.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  

  <ItemGroup>
    <UpToDateCheckInput Remove="UserControls\HighBar\NakopitelDoorControl.axaml" />
  </ItemGroup>
  

  <ItemGroup>
    <Folder Include="UserControls\ControlPage\" />
  </ItemGroup>
  

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  

  <ItemGroup>
    <UpToDateCheckInput Remove="Assets\08.png" />
  </ItemGroup>
  

  <ItemGroup>
    <UpToDateCheckInput Remove="Assets\12.png" />
  </ItemGroup>
</Project>
